resources:
- name: repo
  type: git
  source:
    # changed uri to ssh format
    uri: git@github.com:andrewmcwatters/concourse.git
    # specify branch because it's required for the put step
    branch: main
    private_key: ((private-key))

jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: busybox
      inputs:
      - name: repo
      run:
        path: cat
        args: ["repo/README.md"]
